name: Mensaje Diario Aylin

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python ejecutar.py
